version: '3.8'

services:
  movie-searcher-api:
    container_name: 'movie-searcher-api'
    restart: always
    build:
      context: .
      target: development
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - REDIS_HOST=movie-searcher-redis
      - REDIS_PORT=6380
    depends_on:
      - movie-searcher-redis
    networks:
      - movie-searcher_backend_services

  movie-searcher-redis:
    container_name: 'movie-searcher-redis'
    restart: always
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - movie-searcher_backend_services

networks:
  movie-searcher_backend_services:
    driver: bridge
    
volumes:
  redis_data:
